### ISSUE TITLE
Catch-up on Radio Wien does not work

### ISSUE THREAD

**Issue by sphh** [mopidy/mopidy-orfradio#1]
Brilliant piece of work!! Thanks.

When I want to listen to old broadcasts, I can to it on Ö1. On Radio Wien nothing is played, but the live stream works. I admit that I have not tried any other radio stations. Have they changed the streams? Any chance to get it corrected? That would be really great!!

**Comment by girst** [comment]
good catch! fixed in master. it'll take a while for a release, so i'm keeping the ticket open.

**Comment by sphh** [comment]
I applied the changes _in situ_, restarted `mopidy` and everything works fine! Thanks.

BTW I would not call it a catch. That fish just bumped into me... ;-)

**Comment by girst** [comment]
@sphh, finally we got a release out the door!

**Comment by sphh** [comment]
Thanks a lot, @girst!
