### ISSUE TITLE
Cannot save radio station to Streams page in MMW

### ISSUE THREAD

**Issue by sphh** [mopidy/mopidy-orfradio#2]
I use the [Mopidy MusicBox Webclient (MMW)](https://pypi.org/project/Mopidy-MusicBox-Webclient/) as a front end to `mopidy`. I also have `mopidy-orfradio` installed.

Since I don't fancy to dig down all my to the Ö1 station, I wanted to add the station to the `Streams` page, which saves me a couple of clicks.

I followed the following procedure:
1. I start playing Ö1 by playing it from `Browse > ORF Radio > Ö1 > Ö1 Live`.
2. I go to the `Streams` page.
3. I press the `Get currently playing` button, this fills in the first text box with `orfradio:oe1/live`.
4. I fill out the second text box with `Ö1`.
5. I press the `Save` button and voilà, there is a new entry in the list of streams.

Whenever I revisit the `Streams` page and click on `Ö1` I get the error message, that this is not a valid stream, which I can see. I don't know, if this is MMW's or ORFradio's "fault", but it would be nice to have it working!

**Comment by girst** [comment]
i think this is a bug (or not implemented feature) in musicbox-web. i 
followed your STR to add a stream, then launched ncmpcpp, which played 
the stream just fine (well, i didn't bother adding a soundcard to my 
virtual machine, but it showed metadata and no errors).

i also couldn't see any websocket traffic after clicking to play the 
stream, so i suspect this error message comes from the webui itself.

ping, @kingosticks: ^

as a workaround, you could add the http url of the live stream directly: 
https://oe1shoutcast.sf.apa.at/;
(the semicolon is part of the url; you can also replace the 'oe1' part 
with any of the ids listed in the 3rd column of library.py lines 18-30)

**Comment by kingosticks** [comment]
Musicbox-Webclient can't really do much to get this wrong, it takes the URI of the currently playing track which in this case is apparently 'orfradio:oe1/live'. That's saved to an m3u playlist. It should then be possible to load in that playlist and play the URIs contained within it. The webclient is using all standard Mopidy Core functions to do this:
* `library.lookup(uri)` of each URI in the playlist to get the track metadata
*  `tracklist.add(uri)` to add the track so it can be played.

So I guess my question is: is 'orfradio:oe1/live' a valid URI that you can just lookup and play like normal, or does this backend only support playback of tracks you've browsed to first? After a quick look at the code here, I cannot see how the `shoutcast` attribute would be populated by just doing a `lookup` of a "live" track such as 'orfradio:oe1/live'. Is this supported?

EDIT: ok, I see how that works now. I guess I need to try this all out

**Comment by kingosticks** [comment]
OK, so I followed the problem description and this works for me. I also tried again after restarting Mopidy and loading the previously saved "Streams" entry and it still worked fine. I think we need a log showing the error message.

**Comment by girst** [comment]
On Sun, Jun 21, 2020 at 12:03:10PM -0700, Nick Steel wrote:
>Musicbox-Webclient can't really do much to get this wrong, it takes the 
>URI of the currently playing track which in this case is apparently 
>'orfradio:oe1/live'. That's saved to an m3u playlist. It should then be 
>possible to load in that playlist and play the URIs contained within 

if i create a m3u playlist (using Musicbox-Webclient) with the oe1/live 
stream in it, it is playable with ncmpcpp, but not Musicbox-Webclient.

>So I guess my question is: is 'orfradio:oe1/live' a valid URI that you 
>can just lookup and play like normal, or does this backend only support 

i think it is. see library.py:
141|    def lookup(self, uri):
143|        library_uri = ORFLibraryUri.parse(uri)
...
148|        if library_uri.uri_type == ORFUriType.LIVE:
149|            return [Track(uri=str(library_uri), name="Live")]


>playback of tracks you've browsed to first?

browsing to it first is not necessary. on a freshly started mopidy, 
issuing this just works:

	 mpc add orfradio:oe1/live && mpc play

>After a quick look at the code here, I cannot see how the `shoutcast` 
>attribute would be populated by just doing a `lookup` of a "live" track 
>such as 'orfradio:oe1/live'. Is this supported?

that is handled by playback.py's translate_uri(). client.lookup() 
returns a mopidy.model.Track object.

**Comment by girst** [comment]
On Sun, Jun 21, 2020 at 12:26:10PM -0700, Nick Steel wrote:
>I think we need a log showing the error message.

the request to play the URI never reaches mopidy (at least, i can't 
observe any websocket-traffic or mopidy warnings).

i think it trips over https://github.com/pimusicbox/mopidy-musicbox-webclient/blob/develop/mopidy_musicbox_webclient/static/js/controls.js#L671

671|            if (isServiceUri(nwuri) || isStreamUri(nwuri) || validUri(nwuri)) {
...
681|            } else {
682|                toast('No valid url!')

isStreamUri looks into radioExtensionsList (functionsvars.js:74), which 
has a few extensions whitelisted, but not orfradio.

**Comment by kingosticks** [comment]
You are right, if you try and play it from the streams list it will fail as you say. If you play it from the "Musicbox Favourites" playlist (which has the same contents), it doesn't go down that code path and it works. I thought I tried both methods on Sunday but I guess not. This is certainly a problem with Mopidy-Musicbox-Webclient, not Mopidy-ORFRadio. I hadn't looked at that code in quite a while, thanks for your help @girst.

**Comment by sphh** [comment]
Thanks @girst and @kingosticks for investigating and pinpointing the cause. I did not know, if this issue was in the realm of `mopidy-orfradio` or `mopidy-musicbox-webclient`, but you have to start somewhere, haven't you?

**Comment by kingosticks** [comment]
> but you have to start somewhere, haven't you?

Of course, nothing unreasonable about it. Thanks for reporting.
