### ISSUE TITLE
Live streams do not work anymore?

### ISSUE THREAD

**Issue by Kryophilos** [mopidy/mopidy-orfradio#7]
Hi, I (have) enjoy(ed) this nice mopidy extension a lot, unfortunately, the live streams do not work anymore (at least for me) whereas the 7 day archive is still fine. As I had to change also the Ö3 link in my normal M3U playlist this might be a general issue (URLs may have changed at the ORF), I just cannot tell exactly when the issue has occured (would assume beginning of this year). Could you please have a look at that? Vielen Dank!!

**Comment by girst** [comment]
This looks like a dupe of bug #6. have you updated the extension this 
week to 2.0.3?

**Comment by girst** [comment]
sorry, dupe of *bug #5*, not 6.

**Comment by Kryophilos** [comment]
I do apologise, I did not check the closed issues as I had just updated to 2.0.3 and it was still not working. At the end I have missed to restart the Mopidy daemon; now it seems to work smoothly. Thank you so much and again sorry for my fuss!!
